apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/deepseek-v4-benchmark
    newTag: 2ff2a4755ef3d108d4519a520ebc9f3fc6b662c1
