apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/deepseek-v4-benchmark
    newTag: b4d3406a2b89591132765511cb0b27919cc97254
