apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
images:
  - name: registry.144.91.77.245.sslip.io/deepseek-v4-benchmark
    newTag: 9002400cfb60d45f12f0c5b753ec2af0997ec06a
